environment:
  matrix:
    - nodejs_version: 8
    - nodejs_version: 9

version: "{build}"

cache:
  - node_modules -> package.json

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - yarn

test_script:
  - yarn run test

build: off
deploy: off
