version: 2.1

orbs:
  codacy: codacy/base@4.5.1
  codacy_plugins_test: codacy/plugins-test@0.14.5

jobs:
  node_latest:
    docker:
      - image: circleci/node:latest
    working_directory: ~/workdir
    steps:
      - attach_workspace: 
          at: ~/workdir
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn run test

workflows:
  version: 2
  compile_test_deploy:
    jobs:
      - codacy/checkout_and_version
      - node_latest:
          requires:
            - codacy/checkout_and_version
      - codacy/shell:
          name: publish_docker_local
          cmd: |
            docker build -t $CIRCLE_PROJECT_REPONAME:latest .
            docker save --output docker-image.tar $CIRCLE_PROJECT_REPONAME:latest
          persist_to_workspace: true
          requires:
            - codacy/checkout_and_version
      - codacy_plugins_test/run:
          name: plugins_test
          requires:
            - publish_docker_local
      - codacy/publish_docker:
          context: CodacyDocker
          requires:
            - node_latest
            - plugins_test
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          context: CodacyAWS
          requires:
            - codacy/publish_docker
