version: 2.1

orbs:
  codacy: codacy/base@0.1.0
jobs:
  node_8:
    docker:
      - image: circleci/node:8
    working_directory: ~/workdir
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn run test
      - run: yarn run cov:send

  node_latest:
    docker:
      - image: circleci/node:latest
    working_directory: ~/workdir
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn run test

  publish_docker_locally:
    machine: true
    working_directory: ~/workdir
    steps:
    - checkout
    - attach_workspace:
        at: ~/workdir
    - run:
        name: Publish local docker
        command: docker build --no-cache --tag codacy/codacy-tslint:dev .
    - run:
        name: Save docker to file
        command: |
          mkdir workspace
          docker save --output workspace/codacy-tslint.tar codacy/$CIRCLE_PROJECT_REPONAME:dev
    - persist_to_workspace:
        root: workspace
        paths:
        - codacy-tslint.tar

  publish_dockerhub:
    machine: true
    working_directory: ~/workdir
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load docker from file
          command: docker load --input /tmp/workspace/codacy-tslint.tar
      - run: docker tag codacy/$CIRCLE_PROJECT_REPONAME:dev codacy/$CIRCLE_PROJECT_REPONAME:2.0.$CIRCLE_BUILD_NUM
      - run: docker tag codacy/$CIRCLE_PROJECT_REPONAME:dev codacy/$CIRCLE_PROJECT_REPONAME:latest
      - run: npm run docker:login
      - run: docker push codacy/$CIRCLE_PROJECT_REPONAME:2.0.$CIRCLE_BUILD_NUM
      - run: docker push codacy/$CIRCLE_PROJECT_REPONAME:latest

  integration_tests:
    machine: true
    working_directory: ~/
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load docker from file
          command: docker load --input /tmp/workspace/codacy-tslint.tar
      - run: 
          name: Clone test project
          working_directory: ~/
          command: |
            (git -C ~/codacy-plugins-test fetch --all && 
              git -C ~/codacy-plugins-test reset --hard origin/master) || 
                git clone git://github.com/codacy/codacy-plugins-test.git ~/codacy-plugins-test
      - restore_cache:
          key: dependencies-{{ checksum "~/codacy-plugins-test/build.sbt" }}
      - run: 
          name: Compile test project
          working_directory: ~/codacy-plugins-test
          command: sbt compile
      - save_cache:
          key: dependencies-{{ checksum "~/codacy-plugins-test/build.sbt" }}
          paths:
            - "~/.ivy2"
            - "~/.m2"
            - "~/.sbt"
            - "~/codacy-plugins-test/target"
            - "~/codacy-plugins-test/project/target"
            - "~/codacy-plugins-test/project/project"
      - run: 
          name: Test json
          working_directory: ~/codacy-plugins-test
          command: sbt "runMain codacy.plugins.DockerTest json codacy/$CIRCLE_PROJECT_REPONAME:dev"
      - run:
          name: Test patterns
          working_directory: ~/codacy-plugins-test
          command: sbt -Dcodacy.tests.threads=8 "runMain codacy.plugins.DockerTest pattern codacy/$CIRCLE_PROJECT_REPONAME:dev"

workflows:
  version: 2
  build:
    jobs:
      - node_8
      - node_latest
      - publish_docker_locally
      - integration_tests:
          requires:
            - publish_docker_locally
      - publish_dockerhub:
          context: CodacyDocker
          requires:
            - node_8
            - node_latest
            - publish_docker_locally
            - integration_tests
          filters:
              branches:
                only:
                - master
      - codacy/tag_version:
          name: tag_version
          requires:
            - publish_dockerhub
          filters:
            branches:
              only:
                - master
